name: g_news
description: A news application using Flutter and GetX.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  http: ^0.13.5
  share_plus: ^7.0.2
  url_launcher: ^6.1.11
  shared_preferences: ^2.2.2
  animations: ^2.0.8
  carousel_slider: ^4.2.1
  pull_to_refresh: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true